FROM node:22-bookworm-slim AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci --no-audit --no-fund

FROM node:22-bookworm-slim AS builder
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
ARG NEXT_PUBLIC_MEDUSA_BASE_URL
ARG NEXT_PUBLIC_MEDUSA_PUBLISHABLE_API_KEY
ARG NEXT_PUBLIC_MEDUSA_ADMIN_URL
ARG NEXT_PUBLIC_STORE_NAME
ENV NEXT_PUBLIC_MEDUSA_BASE_URL=$NEXT_PUBLIC_MEDUSA_BASE_URL \
    NEXT_PUBLIC_MEDUSA_PUBLISHABLE_API_KEY=$NEXT_PUBLIC_MEDUSA_PUBLISHABLE_API_KEY \
    NEXT_PUBLIC_MEDUSA_ADMIN_URL=$NEXT_PUBLIC_MEDUSA_ADMIN_URL \
    NEXT_PUBLIC_STORE_NAME=$NEXT_PUBLIC_STORE_NAME
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:22-bookworm-slim AS runner
WORKDIR /app
ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000 \
    HOSTNAME=0.0.0.0

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000

CMD ["node", "server.js"]

